package defaultPackage;

import java.io.Serializable;

public class Patient implements Serializable {

	/**
	 * This UID was generated by Eclipse.
	 */
	private static final long serialVersionUID = 881790700254277680L;
	
	private String[] name;
	private String dob;
	private int health_card_number;
	
	
	public Patient(String[] name, int day, int month, int year, int health_number) {
		this.name = name.clone();
		this.health_card_number = health_number;
		this.dob = String.valueOf(day) + "-" + String.valueOf(month) + "-" + String.valueOf(year);
	}
	
	@Override
	public String toString() {
		String patient_data = "";
		for (String i : name) {
			patient_data += i + " ";
		}
		patient_data += this.dob + "" + String.valueOf(this.health_card_number);
		return patient_data;
		
	}
	
	public static void main (String[] args) {
		
		
		
	}
}
